version: '3'
services:

  regovar_pg:
    container_name: regovar_pg
    image: postgres
    restart: always
    volumes:
      - /var/regovar/pgdata:/var/lib/postgresql/data
      - /var/regovar/databases:/var/regovar/databases
      - /etc/passwd:/etc/passwd:ro
    environment:
      - POSTGRES_USER=regovar
      - POSTGRES_PASSWORD=regovar
      - POSTGRES_DB=regovar
    ports:
      - "8501:5432"
    user: regovar_user


  regovar_app:
    container_name: regovar_app
    build: .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/regovar:/var/regovar
      - localgit/regovar:/var/regovar_app
    ports:
      - "8500:8500"
    depends_on:
      - regovar_pg
    user: regovar_user
    working_dir: /var/regovar_app

      
    
    
    
