version: '3.5'
services:
    
  {docker_pg}:
    container_name: {docker_pg}
    image: postgres
    restart: always
    volumes:
      - {root_path}/pgdata:/var/lib/postgresql/data
      - {root_path}/databases:/var/regovar/databases
      - /etc/passwd:/etc/passwd:ro
      - {root_path}/config/postgres.conf:/etc/postgresql/postgresql.conf
    environment:
      - POSTGRES_USER={db_user}
      - POSTGRES_PASSWORD={db_pwd}
      - POSTGRES_DB={db_name}
    user: {regovar_user}
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    networks:
      - {docker_net}



  {docker_app}:
    container_name: {docker_app}
    build: .
    image: regovar
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - {root_path}:/var/regovar
      - /etc/passwd:/etc/passwd:ro
      - {git_path}/regovar:/var/regovar_app
    ports:
      - "{regovar_port}:{regovar_port}"
    depends_on:
      - {docker_pg}
    working_dir: /var/regovar_app
    command: python regovar.py
    networks:
      - {docker_net}


networks:
  {docker_net}:
    name: {docker_net}
    
    
    
